### ISSUE TITLE
Got Vulnerability warning using `nmap --script vuln`

### ISSUE THREAD

**Issue by clarkorz** [0xB4LINT/nginxconfig.io#94]
![image](https://user-images.githubusercontent.com/3261477/59577959-7f16ca80-90f8-11e9-9171-c771f14aa529.png)
According to [Weak DH](https://weakdh.org) , `Cipher Suites` should not include `DHE-RSA-AES256-GCM-SHA384`.

Suggested cipher suites is: 
```
ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';

ssl_prefer_server_ciphers on;
```

**Comment by 0xB4LINT** [comment]
Thanks for the report!
This vulnerability was present because of the `-dsaparam` flag, which was used to speed up the generation (without insisting to "safe primes").
More about this topic: https://security.stackexchange.com/a/72296

(As I can see there is nothing wrong with `DHE-RSA-AES256-GCM-SHA384` cipher.
